name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - uses: actions/checkout@v4

      
      - uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # 2. Instalar dependencias necesarias
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential googletest

      # 3. Configurar, compilar y ejecutar las pruebas
      - name: Configure, Build, and Test
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .
          ctest --output-on-failure
